import json
import os

def find_workspace_root():
    here = os.path.dirname(os.path.abspath(__file__))
    for cand in (here, os.path.dirname(here)):
        if os.path.isfile(os.path.join(cand, "Cargo.toml")):
            return cand
    raise RuntimeError("could not locate Cargo.toml in current or parent directory")

WORKSPACE_ROOT = find_workspace_root()
ENTITIES_JSON_PATH = os.path.join(WORKSPACE_ROOT, "third_party", "entities.json")
TARGET_RUST_FILE_PATH = os.path.join(WORKSPACE_ROOT, "src", "generated_entities.rs")

# Can't output codepoint as-is because of quote entities.
def to_rust_codepoint(s):
    return "".join("\\u{%04x}" % ord(ch) for ch in s)

def main():
    with open(ENTITIES_JSON_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    entities = {}
    for key, val in data.items():
        name = key[1:]  # Exclude the ampersand
        if name[-1] == ";":
            name = name[:-1]
        entities[name] = val["characters"]

    # MUST be sorted to be ready for binary search
    entities = sorted(entities.items(), key=lambda kv: kv[0])

    lines = [
        "// WARNING: AUTO-GENERATED BY `scripts/generate_entities.py` DO NOT MANUALLY MODIFY THIS FILE!",
        "",
        "pub const ENTITIES: &[(&[u8], &str)] = &["
    ]

    for e, ch in entities:
        lines.append('    (b"%s", "%s"),' % (e, to_rust_codepoint(ch)))
    lines.append("];")
    lines.append("")
    lines.append("pub const MAX_ENTITY_NAME_LEN: usize = %d;" % max(len(e.encode("utf-8")) for e, _ in entities))
    lines.append("") # EOF

    with open(TARGET_RUST_FILE_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

if __name__ == "__main__":
    main()
